---
- name: "Kubernetes | Create an empty file for the containerd module"
  copy:
    content: ""
    dest: /etc/modules-load.d/containerd.conf
    force: no

- name: "Kubernetss | Configure modules for containerd"
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: "Kubernetes | Create containerd directory"
  file:
    path: /etc/containerd
    state: directory

- name: "Kubernetes | Add containerd configuration"
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: "Kubernetes | Configuring Systemd cgroup driver for containerd"
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "            SystemdCgroup = false"
    line:   "            SystemdCgroup = true"

- name: "Kubernetes | Enable the containerd service and start service"
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes
